name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.15.0
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: 'frontend/pnpm-lock.yaml'
    
    - name: Install dependencies
      run: cd frontend && pnpm install
    
    - name: Run linting
      run: cd frontend && pnpm run lint
    
    - name: Run type checking
      run: cd frontend && pnpm run type-check
    
    - name: Build application
      run: cd frontend && pnpm run build
      env:
        JWT_SECRET: "development-secret-key"
        NEXT_PUBLIC_API_URL: "http://localhost:8080"
        NEXT_PUBLIC_API_BASE_URL: "http://localhost:8080/api/v1"
        GATEWAY_URL: "http://localhost:8080"

 