name: cbam

services:
  # API Gateway 서비스
  gateway:
    build: ./gateway
    container_name: cbam-gateway
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL:-http://auth-service:8000}
      - CAL_BOUNDARY_URL=${CAL_BOUNDARY_URL:-http://cal-boundary:8001}
      - CORS_URL=${CORS_URL:-http://localhost:3000}
      - PORT=8080
    depends_on:
      - auth-service
      - cal-boundary
    networks:
      - cbam-network
    restart: unless-stopped

  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15-alpine
    container_name: cbam-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cbam_db
      - POSTGRES_USER=cbam_user
      - POSTGRES_PASSWORD=cbam_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cbam-network
    restart: unless-stopped

  # 인증 서비스
  auth-service:
    build: ./service/auth-service
    container_name: cbam-auth-service
    ports:
      - "8000:8001"
    environment:
      - PORT=8001
      # 로컬 개발용 PostgreSQL 설정
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=cbam_db
      - DB_USER=cbam_user
      - DB_PASSWORD=cbam_password
      # Railway 배포 시 내부 네트워크 사용
      - DATABASE_URL=${DATABASE_URL:-postgresql://cbam_user:cbam_password@postgres:5432/cbam_db}
    depends_on:
      - postgres
    networks:
      - cbam-network
    restart: unless-stopped

  # Cal_boundary 서비스 (실제 폴더명에 맞춤)
  cal-boundary:
    build: ./service/cbam-service
    container_name: cbam-cal-boundary
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - DEBUG_MODE=true
      - DATABASE_URL=${DATABASE_URL:-postgresql://cbam_user:cbam_password@postgres:5432/cbam_db}
    depends_on:
      - postgres
    networks:
      - cbam-network
    restart: unless-stopped

  # Frontend 서비스는 개발 환경에서 직접 실행
  # docker-compose up -d gateway cal-boundary auth-service postgres

networks:
  cbam-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
